chat_gpt_model: 'gpt-4'
openai_embedding_model: 'text-embedding-ada-002'
recursive_text_spliter_chunk_size: 1000
recursive_text_spliter_chunk_overlap: 200
chat_gpt_temp: 0.0
tiktoken_model: 'gpt-3.5-turbo'
tiktoken_embeddings: 'cl100k_base'